# Generated by Django 5.2.7 on 2025-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='runs',
            new_name='ball',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='match_id',
            new_name='dl_applied',
        ),
        migrations.AddField(
            model_name='delivery',
            name='batsman_runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='bye_runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='dismissal_kind',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='fielder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='inning',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_super_over',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='legbye_runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='noball_runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='non_striker',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='over',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='penalty_runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='player_dismissed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='total_runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='wide_runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_of_match',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='toss_decision',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='umpire1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='umpire2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='umpire3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='win_by_runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='win_by_wickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
